export type DomainFeatureFFMapping = Record<string, Record<string, string[]>>

/**
 * Source of truth:
 * https://docs.google.com/spreadsheets/d/1yXx8M48F_YlwaO6X-kyDvPlMLaXO8-HxXPkn9hzSzN4/edit?gid=99010819#gid=99010819
 *
 * Generated by: npm run sync:feature-flags
 */
export const domainFeatureFFMappingRaw: DomainFeatureFFMapping = {
  "Bundles": {
    "AI Receptionist (vcita \\ TPG)": [
      "pickmycallfree_include_in_plan"
    ],
    "Calls & Texting": [
      "callsandtexting_include_in_plan"
    ],
    "Email Signature": [
      "emailsignature_include_in_plan"
    ],
    "Google Analytics": [
      "conversiontracking_include_in_plan"
    ],
    "Pro Campaign Editor": [
      "appadvancecampaigneditor_include_in_plan"
    ],
    "QuickBooks": [
      "appquickbooks_include_in_plan"
    ],
    "Reserve with Google": [
      "googlereserve_include_in_plan"
    ],
    "Unlimited Seats": [
      "unlimited_seats"
    ],
    "Zapier": [
      "api"
    ]
  },
  "License": {
    "Thryv - External New Staff URL": [
      "external_new_staff_url"
    ]
  },
  "AI": {
    "AI Chat": [
      "bizai_chat"
    ],
    "AI Smart Reply": [
      "bizai_smart_reply"
    ],
    "Smart Reply Advanced": [
      "pkg.ai.smart_reply_advanced"
    ],
    "CS Recommendations": [
      "bizai_cs_recommendations"
    ]
  },
  "Client Management": {
    "# of clients": [
      "unlimited_clients"
    ],
    "Email Templates Customization": [
      "pkg.business_administration.email_templates",
      "cliche_client_features",
      "cliche_all_features"
    ],
    "Custom Client Statuses": [
      "enable_client_status_customization"
    ],
    "Custom Client Fields": [
      "allow_custom_field_creation"
    ],
    "Custom Forms/Intake Forms": [
      "enable_forms_customization"
    ],
    "Reviews": [
      "collect_reviews",
      "enable_reviews_auto_publishing"
    ],
    "Documents \\ Storage": [
      "documents_enabled",
      "pkg.documents.promote"
    ],
    "client_portal_credit_cards": [
      "client_portal_credit_cards"
    ]
  },
  "Scheduling": {
    "Basic Scheduling": [
      "scheduling_features"
    ],
    "Services": [
      "single_service_booking",
      "3_services_limitation",
      "unlimited_services",
      "remove_service_limit"
    ],
    "Event Attendees": [
      "event_attendees_limit_increased"
    ],
    "Online Booking": [
      "online_scheduling"
    ],
    "Online Multi-Service Booking": [
      "multi_appointment_client_booking"
    ],
    "Booking Restrictions for New Clients": [
      "booking_restrictions_per_service"
    ],
    "Custom Notification & Reminders": [
      "notifications_per_service"
    ],
    "Custom Fields per Service": [
      "add_custom_field_service"
    ],
    "Waiting List": [
      "event_waitlist"
    ],
    "Arrival window": [
      "arrival_window"
    ],
    "Resources": [
      "pkg.sch.resources"
    ],
    "External Calendar Sync (Google and Outlook)": [
      "external_calendar_sync",
      "googlewaysync_include_in_plan",
      "outlookwaysync_include_in_plan"
    ],
    "Zoom": [
      "zoom_packageable",
      "old_integration_zoom_include_in_plan"
    ]
  },
  "Payments": {
    "Payment Module": [
      "payments_module",
      "pkg.payments.promote"
    ],
    "Invoicing": [
      "invoicing_features",
      "invoices_monthly_unlimited"
    ],
    "Estimates": [
      "payments_feature_estimates",
      "estimates_monthly_unlimited"
    ],
    "Save Cards": [
      "save_cards"
    ],
    "Online Payments": [
      "online_payment"
    ],
    "Recurring Payments": [
      "scheduled_payments"
    ],
    "Templates (Invoices & Estimates Branding)": [
      "pdf_customization"
    ],
    "Packages": [
      "booking_packages"
    ],
    "Coupons": [
      "coupons"
    ],
    "Auto Billing Workflows": [
      "automated_close_balance"
    ],
    "Work Order": [
      "eligible_for_work_order"
    ]
  },
  "Communication": {
    "SMS Module": [
      "sms_enabled",
      "sms_deduct_all_chargeables",
      "purchase_sms_credits"
    ],
    "SMS reminders (for Bookings and Payments)": [
      "sms_client_reminders"
    ],
    "SMS Campaigns": [
      "hide_sms_channel_from_marketing"
    ],
    "Thryv": [
      "tatango",
      "dedicated_promotional_number",
      "bye_zipwip",
      "disable_messages_notifications"
    ],
    "Mute": [
      "mute"
    ]
  },
  "Marketing": {
    "Marketing Module": [
      "marketing_module",
      "pkg.marketing.promote"
    ],
    "Campaign Recipients": [
      "campaign_recipients_monthly_unlimited"
    ],
    "Email Campaigns": [
      "blasts"
    ],
    "Automated Campaigns": [
      "activate_automatic_campaigns",
      "create_delete_automatic_campaigns"
    ],
    "Thryv - Pro Campaigns (as an addon)": [
      "pro_campaigns",
      "send_pro_campaigns",
      "ace_add_on"
    ]
  },
  "Business Administration": {
    "Multi Staff": [
      "multistaff_features",
      "joint_availability",
      "staff_role_permissions",
      "auto_reassign"
    ],
    "App Market": [
      "app_market_available"
    ],
    "Reports": [
      "reports",
      "detailed_reports"
    ],
    "Quick actions": [
      "pkg.business_administration.quick_actions"
    ],
    "Integrations card": [
      "pkg.business_administration.integrations"
    ],
    "Business management upsell": [
      "pkg.bizmanagement.promote"
    ],
    "Onboarding wizard": [
      "pkg.business_administration.registration_wizard.deny",
      "pkg.business_administration.slim_registration_wizard"
    ],
    "Getting Started wizard": [
      "pkg.business_administration.getting_started.deny",
      "setup_wizard_menu_item"
    ],
    "Pendo": [
      "pkg.bus.pendo.deny"
    ],
    "Static Page": [
      "static_page"
    ],
    "vcita - Hide Powered By vcita": [
      "no_powered_by"
    ],
    "vcita - Backoffice Branding": [
      "backoffice_branding"
    ]
  },
  "Trial \\ Spam prevention": {
    "Block Phone Numbers in Messages": [
      "block_phone_numbers_in_messages"
    ],
    "Limit CRM Bulk Actions": [
      "pkg.crm.limit_bulk_actions"
    ],
    "Limit Document Sharing": [
      "limit_document_sharing"
    ],
    "Block Links in Messages": [
      "allow_to_send_link"
    ]
  },
  "Other": {
    "Basic Business Features": [
      "basic_business_features"
    ],
    "Lead Gen Features": [
      "lead_gen_features"
    ],
    "Ultimate Features": [
      "ultimate_features"
    ],
    "No Promotional Links": [
      "no_promotional_links"
    ],
    "Business Hours": [
      "business_hours"
    ],
    "Free Features": [
      "free_features"
    ],
    "Thryv - websites_enabled": [
      "websites_enabled"
    ],
    "Thryv - command_center": [
      "command_center"
    ],
    "vcita - basic_white_label": [
      "basic_white_label"
    ],
    "Thryv - Soci": [
      "soci"
    ],
    "Thryv - Yext Reviews": [
      "yext_reviews",
      "pkg.thryv.listings_settings",
      "reviews_respond",
      "review_publishing"
    ],
    "Thryv - ThryvPay": [
      "thryv_pay",
      "ThryvPay_wizards"
    ],
    "Thryv - Referral widget": [
      "pkg.thryv.referral_widget"
    ],
    "FCR - Yext": [
      "yextApp_include_in_plan"
    ],
    "FCR - Mono web builder": [
      "monowebbuilder_include_in_plan"
    ]
  }
}

function isFlagToken(ff: string): boolean {
  const trimmed = ff.trim()
  return trimmed.length > 0 && !/[\n\r\t]/.test(trimmed)
}

export const domainFeatureFFMappingFlagsOnly: DomainFeatureFFMapping = Object.fromEntries(
  Object.entries(domainFeatureFFMappingRaw).map(([domain, byFeature]) => [
    domain,
    Object.fromEntries(
      Object.entries(byFeature).map(([feature, ffs]) => [feature, ffs.filter(isFlagToken)]),
    ),
  ]),
)

export function flattenDomainFeatureFF(mapping: DomainFeatureFFMapping): Record<string, string[]> {
  const flat: Record<string, string[]> = {}
  for (const [domain, byFeature] of Object.entries(mapping)) {
    const acc: string[] = []
    for (const ffs of Object.values(byFeature)) acc.push(...ffs)
    flat[domain] = acc
  }
  return flat
}

/**
 * Feature-flag → description mapping.
 * Populated from the "description" column in docs/domain-feature-ff-mapping.csv.
 * Descriptions are optional — empty string means no description yet.
 */
export const featureDescriptions: Record<string, string> = {
  unlimited_seats: 'Disable bottom action bar in staff management page',
  emailsignature_include_in_plan: 'For App Email signature builder',
  conversiontracking_include_in_plan: 'Google Analytics app in the App Market (without this ff the user will see upgrade banner)',
  appquickbooks_include_in_plan: '',
  appadvancecampaigneditor_include_in_plan: 'Pro campaign editor app in the App Market (without this ff the user will see upgrade banner)',
  callsandtexting_include_in_plan: 'The calls and texting app is available to purchase and install on the App market.',
  pickmycallfree_include_in_plan: 'Control the availability of the "pickmycallfree" app in the app market for specific subscription packages.',
  googlereserve_include_in_plan: 'Include Google Reserve in plan',
  api: 'Allow integration with Zapier and Quickbooks',
  external_new_staff_url: '',
  bizai_chat: 'Controls the activation of the BizAi Business Assistance chat',
  bizai_smart_reply: 'Enables a content generator for user message replies during conversations',
  'pkg.ai.smart_reply_advanced': 'Advanced smart reply with precalculated responses for direct premium businesses',
  bizai_cs_recommendations: 'Activates the AI recommendation feature, which displays actionable client-facing next steps (generate estimate, schedule appointment)',
  unlimited_clients: 'Allow breaching Client Quota, use client quota if this is not added to the package',
  'pkg.business_administration.email_templates': 'Allow access to the email templates page and settings.',
  cliche_client_features: 'Allow meeting follow up',
  cliche_all_features: 'Allow editing all transactional emails (including staff)',
  enable_client_status_customization: 'Allows status name changes:Allow status name changes, the addition of custom statuses and client status automation',
  allow_custom_field_creation: 'Allows the creation of custom fields',
  enable_forms_customization: 'Enables users to add client/contact fields to forms',
  collect_reviews: 'Enable partners to collect reviews from clients',
  enable_reviews_auto_publishing: 'Controls access to the Auto-Campaign preset for reviews',
  documents_enabled: 'Enable use of documents module',
  'pkg.documents.promote': 'Displays the Documents menu item to users without access and invites them to upgrade',
  client_portal_credit_cards: '',
  scheduling_features: 'SMS booking confirmation, scheduling notice, auto follow up hours, meeting auto response,  charge type, reminders, client card fields no multiline. if this feature is not on there is only in test quota for online scheduling',
  single_service_booking: 'Allow exposing only one service for online booking (in the client portal)',
  '3_services_limitation': '3 service limitation per account. A user will not be able to create more than 3 services.',
  unlimited_services: 'Unlimited online services. Without this FF the business will get only 3 services',
  remove_service_limit: 'Remove the current limit on max number of services in the back office',
  event_attendees_limit_increased: 'allow to have event with more than 5 participants',
  online_scheduling: 'Allow Scheduling appointments from the client portal',
  multi_appointment_client_booking: 'Enable clients to book multiple appointments in a single visit',
  booking_restrictions_per_service: 'Option to restrict online scheduling for new clients (service level)',
  notifications_per_service: 'Edit text and configuration per service of client notifications',
  add_custom_field_service: 'Include add custom field service in plan',
  event_waitlist: 'Enable the option to activate the event waitlist feature',
  arrival_window: 'Adds ability to set estimated arrival time on appt, service & businesses level',
  'pkg.sch.resources': 'Resource management functionality allowing businesses to create, manage and allocate physical resources to services and appointments. Part of INIT-20.',
  external_calendar_sync: 'Include external calendar sync in plan',
  googlewaysync_include_in_plan: 'Google Calendar synchronization app is included in the plan (without this flag the user will see upgrade banner)',
  outlookwaysync_include_in_plan: 'Outlook Calendar synchronization app is included in the plan (without this flag the user will see upgrade banner)',
  zoom_packageable: 'Enable zoom integration in specific packages',
  old_integration_zoom_include_in_plan: 'Zoom app in the App Market (without this ff the user will see upgrade banner)',
  payments_module: 'main payments module feature flag',
  'pkg.payments.promote': 'Most payment-related features are hidden by default, though in certain cases an upgrade prompt is shown',
  invoicing_features: 'Allow invoicing for an account (payments module sub feature)',
  invoices_monthly_unlimited: 'Unlimited Invoices if no quota was defined, make sure invoice quota was defined if this was not added to the package',
  payments_feature_estimates: 'Allow estimates for an account (payments module sub feature)',
  estimates_monthly_unlimited: 'Unlimited Estimates if no quota was defined.  Make sure estimate quota was defined if this was not added to the package',
  save_cards: 'Card on file (vault) - save client credit card info for future payments',
  online_payment: 'Allow clients to pay using client portal, enable Payou form',
  scheduled_payments: '',
  pdf_customization: 'Invoices templates customization',
  booking_packages: 'Track and manage package offers. Sell future visits, sessions and services in bulk (payments sub feature)',
  coupons: 'Allow adding coupons',
  automated_close_balance: 'Automated billing feature',
  eligible_for_work_order: 'Flag to allow the business view a work order',
  sms_enabled: 'The FF will disable all system entry points to booking confirmations and prompt the upgrade banner',
  sms_deduct_all_chargeables: 'deduct all chargeable sms from sms quota (campaigns, reminders, confirmation etc). relevant only for manual directories',
  purchase_sms_credits: 'Allows directories to use quota (only campaign sms will be taken off the quota)',
  sms_client_reminders: 'Allow turning on client reminders',
  hide_sms_channel_from_marketing: 'This option hides SMS channels from the marketing module, both from auto-campaigns and announcements.',
  tatango: 'Enable integration with Tatango for SMS campaigns and Opt-in by keyword (US only)',
  dedicated_promotional_number: 'Feature will assign a dedicated nexmo number for promotional campaigns',
  bye_zipwip: 'migrate zipwip to twilio',
  disable_messages_notifications: 'disable sending and setting "messages" notifications',
  mute: '',
  marketing_module: 'To enable the restriction, it\'s required to *remove* marketing_module feature flag from the relevant plan',
  'pkg.marketing.promote': 'Displays the Marketing menu item to users without access and invites them to upgrade',
  campaign_recipients_monthly_unlimited: 'Unlimited Campaign recipient if no monthly quota was defined. Make sure Campaign recipient quota was defined if this was not added to the package',
  blasts: 'Open Announcment options, with out blast the user will get the quota of campaign credits (by default 3)',
  activate_automatic_campaigns: 'Allow business to activate an automatic campaign, without it there is no automatic campaign to the business but it will be displayed in UI for upsell',
  create_delete_automatic_campaigns: 'Allow business to create or delete Automatic campaign',
  pro_campaigns: 'Pro campaigns app',
  send_pro_campaigns: '',
  ace_add_on: 'Enable ACE as Add-on',
  multistaff_features: 'Allow adding staff',
  joint_availability: 'Client can see availability for all staff (Allow checking the joint availaibility checkbox)',
  staff_role_permissions: 'Allow assigning role of staff members',
  auto_reassign: 'Auto assign client to his staff members based on business setting',
  app_market_available: 'vcita App Market (available on the menu)',
  reports: 'Enabling Reports on the menu',
  detailed_reports: 'Ability to open the actual reports',
  'pkg.business_administration.quick_actions': 'Shows the quick actions widget, the main menu quick actions button, and other quick actions buttons in conversation, inbox, and other places.',
  'pkg.business_administration.integrations': 'Allow the business to access the integrations category from the settings page',
  'pkg.bizmanagement.promote': 'Reveals UI elements, as client card tabs with an upsell banner, prompting an upgrade to the Business Management package',
  'pkg.business_administration.registration_wizard.deny': 'Do not add the registration wizard for a business at account creation.',
  'pkg.business_administration.slim_registration_wizard': 'When the FF is applied to a package, only business info and profession steps are available in the registration wizard.',
  'pkg.business_administration.getting_started.deny': 'Hides the "getting started" wizard from the main and profile menus.',
  setup_wizard_menu_item: 'Setup wizard menu item in pov menu',
  'pkg.bus.pendo.deny': 'Pendo is a 3rd party tool that helps users on-board and learn about new features',
  static_page: 'Shows a single page experience for user, according to the url on directory settings',
  no_powered_by: 'Ability to remove vcita "powered by" links. Relevant only to vcita users',
  backoffice_branding: 'Allow back-office branding (Frontage)',
  block_phone_numbers_in_messages: 'Block phone numbers in messages',
  'pkg.crm.limit_bulk_actions': 'Limits trial users from bulk actions. When enabled, only single-client selection is allowed, and bulk communication options (send message, share document, invite to pay) are disabled.',
  limit_document_sharing: 'Flag to limit sharing documents',
  allow_to_send_link: 'Enable embeding of links in messages without 30 day wait or payment limitation',
  basic_business_features: 'Privilege to turn on reminder in cliche, email signature in vCita, Allow business to mark message as read/unread',
  lead_gen_features: 'Client Source, Conversation Follow up, Private Notes',
  ultimate_features: 'Email template editing in cliche, Setting Service image',
  no_promotional_links: 'Remove vCita promotional links (automatically removed in WLs)',
  business_hours: 'Allow modification of the business hours',

  free_features: 'Privilege to turn on reminder in cliche, email signature in vCita, Allow business to mark message as read/unread',


  websites_enabled: 'Presents \'websites\' button under online presence. Used to hide website in partners like DUDA that have a competitive solution to website.',
  command_center: 'Thryv only - for command center usage (hides inbox, hides SMS settings etc)',
  basic_white_label: 'Used in Admin form , set the account to manual type if the flag exists and it is white label or direcroty admin',
  soci: 'Add social content platform (For Thryv only)',
  yext_reviews: 'View Yext reviews (For Thryv only)',
  'pkg.thryv.listings_settings': 'Show listing settings tile in settings page',
  reviews_respond: 'Allow to responding to review directly from the system (For Thryv only)',
  review_publishing: 'Allow publishing review using Yext in the live site (For Thryv only)',
  thryv_pay: 'Gives (any) user access to ThryvPay and Scheduled Payments under Sales (if payments enabled)',
  ThryvPay_wizards: 'Thryv pay for \'Core wizard\' and \'Payments wizard\'',
  'pkg.thryv.referral_widget': '',
  yextApp_include_in_plan: '',
  monowebbuilder_include_in_plan: '',
  '2way_call_connect': 'Will turn on the “connect call” feature, when a client tries to call the 2way SMS number',
  campaigns_library: 'Open campaign suggestion from verti for both automatic campaigns and announcements',
  campaign_category_type: 'specify if the categories controller should pass entity_type to the categories API',
  campaign_recipient_quota_breached: 'Allow breaching campaign quota - send webhook and charge after',
  hide_register_wizard: 'Used by automation to disable this wizard',
  livesite_to_client_portal: 'remove vitrage from containing client portal in iframe',
  merge_conversations: 'allow to merge',
  multi_matters: 'Allow users to have multi matters',
  new_auto_feature: 'New Auto Feature',
  old_integration_stripe_include_in_plan: 'trial users cant connect to gateways.',
  outlook_2way: 'Outlook new application ',
  partial_booking_packages: 'Display package actions as visible only with an upgrade message (for lower partner plans)',
  phone_support: 'The business is entitled to phone support i.e. display support phone in the system.',
  'pkg.business_administration.getting_started_wizard.deny': 'When the FF is applied to a package, it hides the registration wizard that pops up after account creation.',
  'pkg.platform_administration.thryv_referral_widget': 'Enable Thryv referral widget functionality for platform administration',
  reserve_with_google: 'Allows to see the Reserve with Google integration or App in the App Market',
  'rollout.communication.notification_center_ui_v3': 'Changing the notification center settings page to work with v3 instead of v1/v2',
  sales_by_item_report: 'report tab for sales',
  split_auto_billing: 'split auto billing to auto invoicing & auto reminding',
  uids_search: 'fetch campaign recipients with uids search',
  unlimited_payments: 'Unlimited payments for free packages',
  vcita_payments_features: 'Allows vcita payment gateway (vcitaPay)',
}
